name: Build

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    name: Build ${{ matrix.platform }} (electron-builder)
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: macOS
            package-cmd: pnpm package:macos --publish=never -c.mac.identity=null
            cleanup-path: dist/mac-universal
            artifact-name: Gitify-dist-mac
          - os: windows-latest
            platform: Windows
            package-cmd: pnpm package:win --publish=never
            cleanup-path: dist/win-unpacked
            artifact-name: Gitify-dist-win
          - os: ubuntu-latest
            platform: Linux
            package-cmd: pnpm package:linux --publish=never
            cleanup-path: dist/linux-unpacked
            artifact-name: Gitify-dist-linux
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Build application
        run: pnpm build

      - name: Package for ${{ matrix.platform }}
        run: ${{ matrix.package-cmd }}
        env:
          # For macOS
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}

      - name: Clean up builds
        shell: bash
        run: rm -rfv ${{ matrix.cleanup-path }}

      - name: Upload artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: ${{ matrix.artifact-name }}
          path: dist/
          overwrite: true
