name: Build

on:
  workflow_call:

jobs:
  build-macos:
    name: Build macOS (electron-builder)
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build
      - run: pnpm prepare:remove-source-maps
      - run: pnpm package:macos --publish=never -c.mac.identity=null
        env:
          CSC_LINK: ${{ secrets.mac_certs }}
          CSC_KEY_PASSWORD: ${{ secrets.mac_certs_password }}
      - name: Clean up builds
        run: rm -rfv dist/mac-universal
      - uses: actions/upload-artifact@v4
        with:
          name: Gitify-dist-mac
          path: dist/
          overwrite: true

  build-windows:
    name: Build Windows (electron-builder)
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build
      - run: pnpm prepare:remove-source-maps
      - run: pnpm package:win --publish=never
      - name: Clean up builds
        run: Remove-Item dist/win-unpacked -Recurse
      - uses: actions/upload-artifact@v4
        with:
          name: Gitify-dist-win
          path: dist
          overwrite: true

  build-linux:
    name: Build Linux (electron-builder)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - run: sudo sysctl kernel.unprivileged_userns_clone=1 # See https://github.com/electron/electron/issues/17972#issuecomment-486927073
      - run: pnpm install
      - run: pnpm build
      - run: pnpm prepare:remove-source-maps
      - run: pnpm package:linux --publish=never
      - name: Clean up builds
        run: rm -rfv dist/linux-unpacked
      - uses: actions/upload-artifact@v4
        with:
          name: Gitify-dist-linux
          path: dist
          overwrite: true
