name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: ğŸ” Lint App
    uses: ./.github/workflows/lint.yml

  tests:
    name: ğŸ§ª Tests
    uses: ./.github/workflows/test.yml
    needs: lint

  build:
    name: ğŸ—ï¸ Build
    uses: ./.github/workflows/build.yml
    needs: tests

  release:
    name: ğŸš€ Release
    uses: ./.github/workflows/release.yml
    needs: tests
    permissions: 
      contents: write
    
