name: CI

on:
  push:
    branches:
      - main
      - release/v**
  pull_request:
    branches-ignore: 
      - release/v** # macOS code-signing only works on `push` events, not `pull_request` events

jobs:
  lint:
    name: Lint App
    uses: ./.github/workflows/lint.yml

  tests:
    name: Tests
    uses: ./.github/workflows/test.yml
    needs: lint

  build:
    name: Build
    uses: ./.github/workflows/build.yml
    needs: tests
    if: ${{ !startsWith(github.head_ref, 'release/v') }}

  release:
    name: Release
    uses: ./.github/workflows/release.yml
    needs: tests
    if: ${{ startsWith(github.head_ref, 'release/v') }}
    permissions: 
      contents: write

    
