name: Website

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch: # For manually verify website deployment

permissions:
  contents: read

jobs:
  redeploy-website:
    name: Deploy Website
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK_URL }}
